# Generated by Django 2.2.28 on 2022-11-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addressomyvlgvxxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressomyvlgvxxo',
            name='ca',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
